### PR TITLE
feat: stepper visual improvements

### PR DESCRIPTION
**Pull request by efstajas**
- Restores pretty step height animation
- Hides step overflow while transitioning

### CODE REVIEW

**Review by evvvritt — COMMENTED** [review]
Edit Splits doesn't animate height after loading splits?

**Comment by efstajas** [comment]
> Edit Splits doesn't animate height after loading splits?

Ah, i see what you mean. The stepper only animates height changes between steps, while transitioning — i had a version in between that would animate all height changes, but it looked super glitchy when for example a text field validation error would pop up. For the edit splits modal I'd have two ideas: 

1. fetching splits with an `await` step as the first step and then passing it to the edit step as state (similar to `collect` flow).
2. decoupling the "monitor height and update with animation" logic that we already have in `section-skeleton` and `toggleable` into a generic component that just animates height changes, and re-using this within the edit splits step.

**Comment by evvvritt** [comment]
> 1. fetching splits with an `await` step as the first step and then passing it to the edit step as state (similar to `collect` flow).

this is nice, let's add as an issue?

**Comment by efstajas** [comment]
https://github.com/radicle-dev/drips-app-v2/issues/154

**Review by evvvritt — APPROVED** [review]

**Pull request merged**
