### PR TITLE
Feat: Add Funds & Withdraw Funds flows

### LINKED ISSUE #72: Withdraw flow
A flow that allows the user to withdraw funds from a given token's outgoing balance. 

Designs: https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/Drips-App-V2?node-id=140%3A6124

**🛑 Blocked by "Balances section"**

Image

### PR DESCRIPTION
**Pull request by efstajas**
Resolves #72

### CODE REVIEW

**Review by evvvritt — CHANGES_REQUESTED** [review]
- [x] use token symbol in Stepper titles
- [x] remove/hide "in order to start streaming" text on topup
- [x] add Wallet Balance to topup flow
- [ ] remove amount from button text (awkward/redundant)
- [ ] trying to submit a long digit number crashed the flow (see screenshot)
- [ ] balance didn't update after top-up success

Screen Shot 2022-11-23 at 18 04 38
Screen Shot 2022-11-23 at 18 05 36

**Comment by efstajas** [comment]
https://github.com/radicle-dev/drips-app-v2/issues/122

@evvvritt Created an issue for the decimals crash, because imo the best way to resolve would require a change in the design system.

**Comment by efstajas** [comment]
Re. "balance didn't update after top-up / withdraw", this can happen if the graph doesn't update in time. These flows currently wait for up to around 5 seconds for an update, and say "it might take a while for your dashboard to update" on the success step just in case the graph doesn't update on time. 

This issue includes a point on making the success step dynamically say something like "change pending, your dashboard will update after some time" or "success" depending on whether the graph did or did not yet update at the end of the max timeout: https://github.com/radicle-dev/drips-app-v2/issues/109

Additionally, we might want to change to something more like what you did with the splits section globally where it keeps everything in a loading state until the expected change is found, but I would consider that outside of the scope of this PR.

**Comment by efstajas** [comment]
Everything else is adjusted 👍

**Review by evvvritt — CHANGES_REQUESTED** [review]

**Review by evvvritt — APPROVED** [review]

**Pull request merged**
